let words = [
    { word: "addition", hint: "The process of adding numbers" },
    { word: "meeting", hint: "Event in which people come together" },
    { word: "number", hint: "Math symbol used for counting" },
    { word: "exchange", hint: "The act of trading" },
    { word: "canvas", hint: "Piece of fabric for oil painting" },
    { word: "garden", hint: "Space for planting flower and plant" },
    { word: "position", hint: "Location of someone or something" },
    { word: "feather", hint: "Hair-like outer covering of bird" },
    { word: "comfort", hint: "A pleasant feeling of relaxation" },
    { word: "tongue", hint: "The muscular organ of mouth" },
    { word: "expansion", hint: "The process of increase or grow" },
    { word: "country", hint: "A politically identified region" },
    { word: "group", hint: "A number of objects or persons" },
    { word: "taste", hint: "Ability of tongue to detect flavor" },
    { word: "store", hint: "Large shop where goods are traded" },
    { word: "field", hint: "Area of land for farming activities" },
    { word: "friend", hint: "Person other than a family member" },
    { word: "pocket", hint: "A bag for carrying small items" },
    { word: "needle", hint: "A thin and sharp metal pin" },
    { word: "expert", hint: "Person with extensive knowledge" },
    { word: "statement", hint: "A declaration of something" },
    { word: "second", hint: "One-sixtieth of a minute" },
    { word: "library", hint: "Place containing a collection of books" },
    { word: "pencil", hint: "Tool used for writing or drawing" },
    { word: "bottle", hint: "Container for holding liquids" },
    { word: "rocket", hint: "A vehicle used to travel into space" },
    { word: "island", hint: "Land surrounded by water" },
    { word: "bridge", hint: "Structure to cross over water or roads" },
    { word: "guitar", hint: "Musical instrument with strings" },
    { word: "window", hint: "Opening in a wall for light or air" },
    { word: "teacher", hint: "A person who imparts knowledge" },
    { word: "planet", hint: "A celestial body orbiting a star" },
    { word: "kitchen", hint: "Room for cooking and food preparation" },
    { word: "school", hint: "Place where children are educated" },
    { word: "doctor", hint: "A medical professional" },
    { word: "circle", hint: "A round shape" },
    { word: "letter", hint: "Written message sent to someone" },
    { word: "bicycle", hint: "A two-wheeled mode of transportation" },
    { word: "laptop", hint: "Portable personal computer" },
    { word: "mobile", hint: "Portable communication device" },
    { word: "mirror", hint: "Reflective surface" },
    { word: "camera", hint: "Device used to capture photos" },
    { word: "jungle", hint: "Dense tropical forest" },
    { word: "ocean", hint: "Large body of saltwater" },
    { word: "pirate", hint: "Person who robs at sea" },
    { word: "prison", hint: "Place for confinement of criminals" },
    { word: "desert", hint: "Dry and sandy land area" },
    { word: "hunger", hint: "Feeling of needing food" },
    { word: "family", hint: "Group of related individuals" },
    { word: "danger", hint: "The possibility of harm or risk" },
    { word: "garden", hint: "Space for growing plants and flowers" },
    { word: "monkey", hint: "Animal known for climbing trees" },
    { word: "butter", hint: "Fat spread made from milk or cream" },
    { word: "police", hint: "Authorities enforcing law and order" },
    { word: "statue", hint: "Carved or cast figure of a person or animal" },
    { word: "wallet", hint: "Small case for carrying money" },
    { word: "shadow", hint: "Dark shape caused by an object blocking light" },
    { word: "castle", hint: "Large fortified building" },
    { word: "butterfly", hint: "Colorful insect with large wings" },
    { word: "volcano", hint: "Mountain with molten rock eruption" },
    { word: "shelter", hint: "Structure providing protection" },
    { word: "advice", hint: "Guidance or recommendations" },
    { word: "clothes", hint: "Garments for wearing" },
    { word: "desire", hint: "Strong feeling of wanting something" },
    { word: "energy", hint: "Capacity to do work" },
    { word: "forest", hint: "Large area covered with trees" },
    { word: "palace", hint: "Large and grand residence" },
    { word: "signal", hint: "Indication or transmission of information" },
    { word: "banana", hint: "Long yellow tropical fruit" },
    { word: "village", hint: "Small settlement of people" },
    { word: "glacier", hint: "Mass of slowly moving ice" },
    { word: "stadium", hint: "Venue for sports or concerts" },
    { word: "sunset", hint: "Evening view when the sun sets" },
    { word: "river", hint: "Natural flowing watercourse" },
    { word: "cloud", hint: "Mass of water vapor in the sky" },
    { word: "future", hint: "Time that is yet to come" },
    { word: "prince", hint: "Male royal family member" },
    { word: "secret", hint: "Information not known to others" },
    { word: "singer", hint: "Person who performs songs" },
    { word: "pillow", hint: "Soft cushion for sleeping" },
    { word: "whistle", hint: "Sharp sound made by blowing air" },
    { word: "globe", hint: "Model of the Earth" },
    { word: "dolphin", hint: "Intelligent marine mammal" },
    { word: "bridge", hint: "Path over an obstacle like a river" },
    { word: "harbor", hint: "Sheltered area for ships" },
    { word: "mountain", hint: "Large natural elevation of earth's surface" },
    { word: "railway", hint: "Tracks for trains to travel on" },
    { word: "factory", hint: "Place where goods are manufactured" },
    { word: "compass", hint: "Instrument showing direction" },
    { word: "trumpet", hint: "Brass musical instrument" },
    { word: "notebook", hint: "Book for writing notes" },
    { word: "diamond", hint: "Precious stone often used in jewelry" },
    { word: "stadium", hint: "Large structure for sports or concerts" },
    { word: "theater", hint: "Building for stage performances or movies" },
    { word: "gardenia", hint: "A fragrant flowering plant" },
    { word: "rainbow", hint: "Colorful arc seen after rain" },
    { word: "horizon", hint: "Line where sky meets land or sea" },
    { word: "calendar", hint: "Chart of days, weeks, and months" },
    { word: "journey", hint: "Act of traveling from one place to another" },
    { word: "science", hint: "Study of natural phenomena" },
    { word: "lantern", hint: "Portable light source" },
    { word: "mountain", hint: "Large natural elevation" },
    { word: "penguin", hint: "Flightless bird found in cold regions" },
    { word: "picture", hint: "Visual representation captured or drawn" },
    { word: "suitcase", hint: "Case used for carrying clothes when traveling" },
    { word: "diamond", hint: "Precious stone" },
    { word: "elephant", hint: "Large mammal with a trunk" },
    { word: "fireplace", hint: "Place in a house for a fire" },
    { word: "helicopter", hint: "Aircraft with rotating blades" },
    { word: "icicle", hint: "Hanging piece of ice formed by dripping water" },
    { word: "journey", hint: "Act of traveling" },
    { word: "kangaroo", hint: "Animal with strong hind legs for hopping" },
    { word: "lemonade", hint: "Beverage made from lemons" },
    { word: "mermaid", hint: "Mythical creature with fish tail and human upper body" },
    { word: "necklace", hint: "Piece of jewelry worn around the neck" },
    { word: "ostrich", hint: "Large flightless bird" },
    { word: "pyramid", hint: "Triangular structure from ancient Egypt" },
    { word: "quicksand", hint: "Loose sand that swallows objects" },
    { word: "raincoat", hint: "Clothing worn to protect from rain" },
    { word: "sandcastle", hint: "Structure made from wet sand" },
    { word: "telephone", hint: "Device for voice communication" },
    { word: "umbrella", hint: "Device for protection against rain" },
    { word: "vampire", hint: "Mythical creature that feeds on blood" },
    { word: "whirlpool", hint: "Spinning body of water" },
    { word: "xylophone", hint: "Musical instrument with wooden bars" },
    { word: "yacht", hint: "Luxury boat" },
    { word: "zebra", hint: "Striped horse-like animal" },
    { word: "anchor", hint: "Heavy object used to moor a ship" },
    { word: "balloon", hint: "Inflatable object" },
    { word: "cactus", hint: "Plant adapted to hot climates" },
    { word: "dungeon", hint: "Underground prison cell" },
    { word: "engineer", hint: "Person who designs or builds things" },
    { word: "fortune", hint: "Great wealth or luck" },
    { word: "glasses", hint: "Eyewear to correct vision" },
    { word: "hammock", hint: "Hanging bed made of fabric or rope" },
    { word: "iguana", hint: "Large tropical lizard" },
    { word: "jewelry", hint: "Decorative items worn for adornment" },
    { word: "kitchen", hint: "Room for cooking" },
    { word: "ladder", hint: "Tool for climbing" },
    { word: "mountain", hint: "Elevated part of Earth's crust" },
    { word: "novelist", hint: "Author of novels" },
    { word: "orchard", hint: "Field where fruit trees are grown" },
    { word: "paradise", hint: "Place of perfect happiness" },
    { word: "quilt", hint: "Warm bed covering made of fabric layers" },
    { word: "reindeer", hint: "Deer species in cold regions" },
    { word: "satellite", hint: "Object orbiting a planet" },
    { word: "treasure", hint: "Valuable items hidden or collected" },
    { word: "universe", hint: "All of space and everything in it" },
    { word: "volcano", hint: "Mountain that erupts lava" },
    { word: "waterfall", hint: "Water flowing over a vertical drop" },
    { word: "yogurt", hint: "Dairy product made by fermentation" },
    { word: "zeppelin", hint: "Airship" },
    { word: "archery", hint: "Sport of shooting arrows" },
    { word: "blueprint", hint: "Technical drawing or design" },
    { word: "crystal", hint: "Solid material with a natural geometric shape" },
    { word: "dragon", hint: "Mythical fire-breathing creature" },
    { word: "envelope", hint: "Paper container for letters" },
    { word: "firetruck", hint: "Vehicle used to extinguish fires" },
    { word: "galaxy", hint: "Large system of stars" },
    { word: "harvest", hint: "Act of gathering crops" },
    { word: "igloo", hint: "House made of ice blocks" },
    { word: "journal", hint: "Diary or record of events" },
    { word: "kingdom", hint: "Territory ruled by a king or queen" },
    { word: "labyrinth", hint: "Complex maze" },
    { word: "meadow", hint: "Field of grass and wildflowers" },
    { word: "notebook", hint: "A book for writing notes" },
    { word: "opera", hint: "A dramatic performance with music and singing" },
    { word: "penguin", hint: "Flightless bird found in cold climates" },
    { word: "quiver", hint: "A case for carrying arrows" },
    { word: "ribbon", hint: "Narrow strip of fabric" },
    { word: "submarine", hint: "Underwater vessel" },
    { word: "typewriter", hint: "Device for typing text on paper" },
    { word: "volleyball", hint: "Sport played with a ball over a net" },
    { word: "watchtower", hint: "Structure for observing surroundings" },
    { word: "x-ray", hint: "Imaging technique using radiation" },
    { word: "amethyst", hint: "Purple gemstone" },
    { word: "bookstore", hint: "Shop selling books" },
    { word: "carpenter", hint: "Person who works with wood" },
    { word: "dandelion", hint: "Yellow-flowered weed" },
    { word: "easel", hint: "Stand used by painters" },
    { word: "fireworks", hint: "Explosive devices for celebrations" },
    { word: "greenhouse", hint: "Structure for growing plants" },
    { word: "hedgehog", hint: "Small mammal with spines" },
    { word: "inkwell", hint: "Container for ink" },
    { word: "jigsaw", hint: "Puzzle with interlocking pieces" },
    { word: "kaleidoscope", hint: "Tube with changing colorful patterns" },
    { word: "lighthouse", hint: "Tower with a light to guide ships" },
    { word: "moonlight", hint: "Light from the moon" },
    { word: "nutcracker", hint: "Tool for cracking nuts" },
    { word: "orchid", hint: "Exotic flowering plant" },
    { word: "pancakes", hint: "Flat cakes cooked on a griddle" },
    { word: "quartz", hint: "Common mineral used in jewelry" },
    { word: "rockingchair", hint: "Chair that rocks back and forth" },
    { word: "sandstorm", hint: "Strong wind carrying sand particles" },
    { word: "treetop", hint: "Topmost part of a tree" },
    { word: "umbrella", hint: "Tool used for protection from rain or sun" },
    { word: "violinist", hint: "Person who plays the violin" },
    { word: "wheelchair", hint: "Chair with wheels for mobility" },
    { word: "yacht", hint: "Luxury sailing vessel" },
    { word: "zookeeper", hint: "Person who cares for animals in a zoo" },
    { word: "anchor", hint: "Device to secure a ship" },
    { word: "ballerina", hint: "Female ballet dancer" },
    { word: "caterpillar", hint: "Larva of a butterfly or moth" },
    { word: "dolphin", hint: "Intelligent marine mammal" },
    { word: "emerald", hint: "Green gemstone" },
    { word: "fountain", hint: "Structure with flowing water" },
    { word: "gladiator", hint: "Ancient Roman fighter" },
    { word: "hummingbird", hint: "Small bird that hovers and drinks nectar" },
    { word: "jackhammer", hint: "Pneumatic tool for breaking hard surfaces" },
    { word: "keepsake", hint: "Small item kept as a memory" },
    { word: "lantern", hint: "Portable light source" },
    { word: "mountaineer", hint: "Person who climbs mountains" },
    { word: "nightingale", hint: "Bird known for its melodious song" },
    { word: "oyster", hint: "Shellfish that produces pearls" },
    { word: "piano", hint: "Musical instrument with keys" },
    { word: "quarantine", hint: "Isolation to prevent disease spread" },
    { word: "rainforest", hint: "Dense tropical forest" },
    { word: "seashell", hint: "Hard outer covering of marine mollusks" },
    { word: "telegraph", hint: "Old communication device using Morse code" },
    { word: "unicorn", hint: "Mythical horse with a single horn" },
    { word: "vulture", hint: "Bird of prey feeding on carcasses" },
    { word: "whirlpool", hint: "Spinning vortex of water" },
    { word: "xerox", hint: "Photocopying machine" },
    { word: "yawning", hint: "Act of opening mouth wide when tired" },
    { word: "astronaut", hint: "Person who travels in space" },
    { word: "blacksmith", hint: "Person who forges metal" },
    { word: "camouflage", hint: "Concealment by blending in" },
    { word: "earthquake", hint: "Sudden shaking of the ground" },
    { word: "firefighter", hint: "Person who extinguishes fires" },
    { word: "goldsmith", hint: "Craftsperson working with gold" },
    { word: "hippopotamus", hint: "Large aquatic mammal" },
    { word: "jellyfish", hint: "Marine animal with tentacles" },
    { word: "kitesurfing", hint: "Water sport using a kite and board" },
    { word: "labyrinth", hint: "Complex maze-like structure" },
    { word: "megaphone", hint: "Device for amplifying voice" },
    { word: "nectarine", hint: "Smooth-skinned fruit similar to a peach" },
    { word: "octopus", hint: "Sea creature with eight arms" },
    { word: "panorama", hint: "Wide view of a surrounding area" },
    { word: "quicksand", hint: "Loose wet sand that pulls objects under" },
    { word: "rocketship", hint: "Vehicle for space travel" },
    { word: "scarecrow", hint: "Figure used to scare birds away from crops" },
    { word: "telescope", hint: "Instrument for viewing distant objects" },   
    { word: "underpass", hint: "Road or walkway beneath another road" },
    { word: "volkswagen", hint: "Car brand name" },
    { word: "watermelon", hint: "Large fruit with green rind and red flesh" },
    { word: "xylophonist", hint: "Person who plays the xylophone" },
    { word: "yardstick", hint: "Measuring stick one yard long" },
    { word: "zeppelin", hint: "Large rigid airship" }
];

console.log(words)